# Generated by Django 5.2.1 on 2025-05-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
